---
- name: Ensure ssh is installed
  package:
    name: openssh
- name: Install screen
  package:
    name: screen
- name: Copy sshd_config into place
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: 0600
    owner: root
    group: root
    backup: yes
  notify: sshd_service
